routes/admin.php
<?php

Route::get('/login', 'Auth\LoginController@showLoginForm')->name('admin.login');
Route::post('/login', 'Auth\LoginController@login');
Route::get('/forgot-password', 'Auth\LoginController@showForgotForm')->name('admin.forgot-password');


Route::group(['middleware' => ['admin', 'admin.auth', 'admin.menu']], function () {
    Route::match(array('GET', 'POST'), '/logout', 'DashboardController@logout')->name('admin.logout');
    Route::any('/', 'DashboardController@index')->name('admin.home');

    Route::resource('/pages', 'PagesController', ['as' => 'admin']);
    Route::resource('/users', 'UsersController', ['as' => 'admin']);
    Route::get('/users/{id}/profile', 'UsersController@editProfile')->name('admin.users.profile');
    Route::put('/users/{id}/profile', 'UsersController@updateProfile')->name('admin.users.profile-store');
    Route::get('/users/{id}/security', 'UsersController@editSecurity')->name('admin.users.security');
    Route::put('/users/{id}/security', 'UsersController@updateSecurity')->name('admin.users.security-store');
    Route::get('/users/{id}/appointments', 'UsersController@listAppointments')->name('admin.users.appointments');
    Route::get('/users/{id}/appointments/{appointmentId}', 'UsersController@showAppointment')->name('admin.users.appointments.detail');
    Route::put('/users/{id}/appointments', 'UsersController@updateAppointments')->name('admin.users.appointments-store');


    Route::resource('/providers', 'ProvidersController', ['as' => 'admin']);
    Route::get('/providers/{id}/profile', 'ProvidersController@editProfile')->name('admin.providers.profile');
    Route::put('/providers/{id}/profile', 'ProvidersController@updateProfile')->name('admin.providers.profile-store');
    Route::get('/providers/{id}/security', 'ProvidersController@editSecurity')->name('admin.providers.security');
    Route::put('/providers/{id}/security', 'ProvidersController@updateSecurity')->name('admin.providers.security-store');
    Route::get('/providers/{id}/appointments', 'ProvidersController@listAppointments')->name('admin.providers.appointments');
    Route::get('/providers/{id}/appointments/{appointmentId}', 'ProvidersController@showAppointment')->name('admin.providers.appointments.detail');
    Route::put('/providers/{id}/appointments', 'ProvidersController@updateAppointments')->name('admin.providers.appointments-store');
    Route::get('/providers/{id}/prices', 'ProvidersController@showPrices')->name('admin.providers.prices');
    Route::put('/providers/{id}/prices', 'ProvidersController@updatePrices')->name('admin.providers.prices-store');
    Route::get('/providers/{id}/gallery', 'ProvidersController@showGallery')->name('admin.providers.gallery');
    Route::delete('/providers/delete-image/{galleryId}', 'ProvidersController@deleteImageGallery')->name('admin.providers.gallery-delete-image');
    Route::post('/providers/{id}/gallery', 'ProvidersController@updateGallery')->name('admin.providers.gallery-store');
    Route::get('/providers/{id}/identity', 'ProvidersController@showIdentity')->name('admin.providers.identity');
    Route::put('/providers/{id}/identity', 'ProvidersController@showIdentity')->name('admin.providers.identity-store');

    Route::get('/appointments', 'AppointmentsController@index')->name('admin.appointments');
    Route::get('/appointments/{id}', 'AppointmentsController@show')->name('admin.appointments.show');

    Route::get('/maps/providers', 'MapsController@showProvidersMap')->name('admin.maps.providers');

    Route::get('/currencies', 'CurrenciesController@show')->name('admin.currencies');
    Route::put('/currencies', 'CurrenciesController@update')->name('admin.currencies.update');

    Route::resource('/automessages', 'AutoMessagesController', ['as' => 'admin']);

    Route::resource('/chats', 'ChatsController', ['as' => 'admin']);

    Route::get('/settings', 'SettingsController@index')->name('admin.settings');
    Route::post('/settings', 'SettingsController@save')->name('admin.settings.save');
    Route::get('/clear-cache', 'SettingsController@clearCache')->name('admin.artisan.cache-clear');
});

routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

Route::get('/resources/lang.json', 'LangController@index');
Route::get('/images/{section}/{folder}/{thumb}/{filename}', array('as' => 'imgs', 'uses' => 'ImagesController@dispatchImage'));
//Route::get('/downloads/resources/{uniqueId}', 'ResourceFilesController@download')->name('resources.download');


#Route::get('/', 'AngularController@serve');
#Route::get('{any?}', 'AngularController@serve')->where('any', '.*'); // this will ensure all routes will serve index.php file

app/Http/Controllers/Admin/UsersController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Admin\Controller;
use App\Models\User;

class UsersController extends Controller {

    public function index(\App\DataTables\Admin\UsersDataTable $dataTable) {
        /* $savedFilter = $this->getRequestSavedParams('users.index');
          if ($savedFilter) {
          return redirect()->to(route('admin.users.index', $savedFilter));
          }
          $this->saveRequestToSession('users.index'); */
        return $dataTable->render('admin.users.index');
    }

    public function show(Request $request, $id) {

        return $this->edit($request, $id);
    }

    public function edit(Request $request, $id) {
        $user = User::where(['id' => $id, 'role' => 'USER'])->with(['profile'])->firstOrFail();
        if (!$user->profile) {
            $user->profile()->save(new \App\Models\UserProfile());
        }
        $user->profile;
        return view('admin.users.detail')->with(['model' => $user, 'profile' => $user->profile, 'tab' => 'basic']);
    }

    public function editProfile(Request $request, $id) {
        $user = User::where(['id' => $id, 'role' => 'USER'])->with(['profile'])->firstOrFail();
        if (!$user->profile) {
            $user->profile()->save(new \App\Models\UserProfile());
        }
        $user->profile;
        return view('admin.users.detail')->with(['model' => $user, 'profile' => $user->profile, 'tab' => 'profile']);
    }

    public function update(Request $request, $id) {
        $user = User::where(['id' => $id, 'role' => 'USER'])->firstOrFail();
        $validator = User::getValidator($request->input(), $user);
        if ($validator->fails()) {
            return redirect()->back()->withInput()->withErrors($validator);
        }



        $user->profile()->updateOrCreate(['user_id' => $user->id], $request->input('profile', []));
        $user->update($request->input());


        if ($request->file('image')) {
            $user->saveImage($request->file('image'));
            $user->save();
        }

        return redirect()->back()->withInput()->with(['message' => 'Usuario guardado correctamente!']);
    }

    public function updateProfile(Request $request, $id) {
        $user = User::where(['id' => $id, 'role' => 'USER'])->firstOrFail();
        $validator = User::getValidator($request->input(), $user);
        if ($validator->fails()) {
            return redirect()->back()->withInput()->withErrors($validator);
        }
        $user->profile()->updateOrCreate(['user_id' => $user->id], $request->input('profile', []));
        $user->update($request->input());
        return redirect()->back()->withInput()->with(['message' => 'Usuario guardado correctamente!']);
    }

    public function editSecurity(Request $request, $id) {
        $user = User::where(['id' => $id, 'role' => 'USER'])->with(['profile'])->firstOrFail();

        return view('admin.users.detail')->with(['model' => $user, 'profile' => $user->profile, 'tab' => 'security']);
    }

    public function updateSecurity(Request $request, $id) {
        $user = User::where(['id' => $id, 'role' => 'USER'])->with(['profile'])->firstOrFail();
        if ($request->get('password')) {
            $user->password = \Illuminate\Support\Facades\Hash::make($request->get('password'));
        }

        if ($request->get('phone_verified')) {
            $user->phone_verified = 1;
        }
        $user->save();
        if ($request->get('password')) {
            \App\Lib\SMSManager::getInstance()->sendSMS($user->completePhone(), 'Hola ' . $user->name . ' tu nuevo password en vaceate.com es ' . $request->get('password'));
        }
        return redirect()->back()->withInput()->with(['message' => 'Usuario guardado correctamente!']);
    }

    public function listAppointments(Request $request, \App\DataTables\Admin\AppointmentsDataTable $dataTable, $id) {
        $user = User::where(['id' => $id, 'role' => 'USER'])->with(['profile'])->firstOrFail();
        return $dataTable->with(['user' => $user, 'status' => $request->get('status', 'all')])->render('admin.users.detail', ['model' => $user, 'tab' => 'appointments']);
    }

    public function showAppointment(Request $request, $id, $appointmentId) {
        $user = User::where(['id' => $id, 'role' => 'USER'])->with(['profile'])->firstOrFail();
        $appointment = \App\Models\Appointment::where(['id' => $appointmentId, 'provider_id' => $id])->firstOrFail();
        return view('admin.appointments.detail', ['model' => $appointment, 'backUrl' => route('admin.users.appointments', ['id' => $id])]);
    }

}

app/Http/Controllers/Api/Admin/UsersController.php
<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

namespace App\Http\Controllers\Api\Admin;

use Illuminate\Http\Request;
use App\Models\User;
use Illuminate\Support\Facades\Hash;

/**
 * Description of ProvidersController
 *
 * @author pablo
 */
class UsersController extends \App\Http\Controllers\Api\BaseController
{

    public function __construct()
    {
        if (!$this->getUser() || ($this->getUser()->role != 'ADMIN')) {
            abort(403);
        }
    }

    public function all(Request $request)
    {
        $users = User::with('profile', 'country')->where(['role' => 'USER', 'status' => 'ACTIVE'])->orderBy('name', 'asc');
        $response = $this->getResponseInstance();
        $response->setPayload($users->get());
        return $this->renderResponse();
    }

    public function index(Request $request)
    {
        $order = $request->get('order', 'name');
        $dir = 'ASC';
        if (strpos($order, '-') === 0) {
            $dir = 'DESC';
            $order = substr($order, 1);
        }
        $users = User::with('profile', 'country')->where(['role' => 'USER'])->orderBy($order, $dir);

        if ($request->input('status') != '' && $request->input('status') != 'all') {
            $users->where(function ($q) use ($request) {
                $q->where(['role' => 'USER', 'status' => $request->input('status')]);
            });
        }

        if ($request->input('query')) {
            $users->where(function ($q) use ($request) {
                $q->where('name', 'LIKE', '%' . $request->input('query') . '%')
                    ->orWhere('phone', 'LIKE', $request->input('query') . '%');
            });
        }

        $paginator = $users->paginate($request->get('count', 20));
        $response = $this->getResponseInstance();
        $response->setPayload($paginator);
        return $this->renderResponse();
    }

    public function show(Request $request, $id)
    {
        $response = $this->getResponseInstance();
        $user = User::with(['profile', 'refereds'])->where(['role' => 'USER', 'id' => $id])->firstOrFail();
        if (!$user->profile) {
            $user->porifle = new \App\Models\UserProfile(['user_id', $user->id]);
            $user->profile->save();
        }
        $response->setPayload($user);
        return $this->renderResponse();
    }


    public function updateSecurity(Request $request, $id)
    {
        $user = User::where(['id' => $id, 'role' => 'USER'])->with(['profile'])->firstOrFail();
        if ($request->get('password')) {
            $user->password = \Illuminate\Support\Facades\Hash::make($request->get('password'));
        }

        if ($request->get('phone_verified')) {
            $user->phone_verified = 1;
        }
        $user->save();
        if ($request->get('password')) {
            //\App\Lib\SMSManager::getInstance()->sendSMS($user->completePhone(), 'Hola ' . $user->name . ' tu nuevo password en vaceate.com es ' . $request->get('password'));
        }
        $response = $this->getResponseInstance();
        $response->setStatusMessage('Usuario guardado correctamente');
        return $this->renderResponse();
    }

    public function update(Request $request, $id)
    {
        $user = User::where(['id' => $id, 'role' => 'USER'])->firstOrFail();
        $validator = User::getValidator($request->input(), $user);
        $response = $this->getResponseInstance();
        if ($validator->fails()) {
            $response->setHttpCode(400);
            $response->setStatusMessage('Datos incorrectos');
            $response->setValidator($validator);
            return $this->renderResponse();
        }



        $user->profile()->updateOrCreate(['user_id' => $user->id], $request->input('profile', []));
        $user->update($request->input());

        $priceOptions = config('custom.price_options');
        if ($request->get('prices')) {
            $user->prices()->delete();
            $prices = collect($request->get('prices'));
            foreach ($priceOptions as $key) {
                $fprice = isset($prices[$key]) ?$prices[$key]['value'] : 0;
                $price = [];
                $price['hours'] = $key;
                $price['provider_id'] = $user->id;
                $price['currency'] = 'USD';
                $price['value'] = $fprice;
                $sPrice = \App\Models\ProviderPrice::create($price);
            }
        }

        if ($request->file('image')) {
            $user->saveImage($request->file('image'));
            $user->save();
        }

        $response->setPayload($user);


        return $this->show($request, $id);
    }

    public function changePassword(Request $request, $id)
    {
        $user = User::where(['role' => 'USER', 'id' => $id])->firstOrFail();
        $validator = validator($request->input(), [
            'password' => 'required|min:6'
        ]);
        $response = $this->getResponseInstance();
        if ($validator->fails()) {
            $response->setHttpCode(400);
            $response->setStatusMessage('Datos incorrectos');
            $response->setValidator($validator);
            return $this->renderResponse();
        }
        $user->password = Hash::make($request->get('password'));
        $user->save();
        return $this->show($request, $id);
    }

    public function refereds(Request $request, $id)
    {
        $response = $this->getResponseInstance();
        $user = User::where(['role' => 'USER', 'id' => $id])->firstOrFail();
        $response->setPayload($user->refereds()->orderBy('name')->get());
        return $this->renderResponse();
    }
}

app/Http/Controllers/Api/UsersController.php
<?php

namespace App\Http\Controllers\Api;

use Illuminate\Http\Request;
use App\Http\Resources\UserCollection;

class UsersController extends BaseCRUDController {

    public function __construct() {
        parent::__construct('\App\Models\User', 'user');
    }

    protected function getDefaultColumns(Request $request) {
        $fields = '["id", "name", "country_id", "role", "presence"]';

        if($this->userHasRole('ADMIN')){
            $fields = '["*"]';
        }

        return $fields;
    }
    
    protected function changeQuery(Request $request, $query) {
        $query->with('profile');
    }

}

resources/views/admin/users/tabs/appointments.blade.php
<div class="top-filter clearfix">
    <div class="btn-group pull-right">
        <a href="{{ route('admin.users.appointments', ['id'=>$model->id, 'status'=>'active'])}}" class="btn btn-default @if(request('status')=='' || request('status')=='active') active @endif">Activos</a>
        <a href="{{ route('admin.users.appointments', ['id'=>$model->id, 'status'=>'pending'])}}" class="btn btn-default @if(request('status')=='pending') active @endif">Pendientes</a>
        <a href="{{ route('admin.users.appointments', ['id'=>$model->id, 'status'=>'finalized'])}}" class="btn btn-default @if(request('status')=='finalized') active @endif">Finalizados</a>
        <a href="{{ route('admin.users.appointments', ['id'=>$model->id, 'status'=>'all'])}}" class="btn btn-default @if(request('status')=='all') active @endif">Todos</a>
    </div>
</div>




{!! $dataTable->table(['class' => 'table table-bordered table-striped dataTable', 'id' => 'users-appointments-table-' . $model->id]) !!}


@push('scripts')
{!! $dataTable->scripts() !!}

@endpush

resources/views/admin/users/tabs/basic.blade.php
@include('admin.users.form', ['action'=>route('admin.users.update', $model->id)])

resources/views/admin/users/tabs/gallery.blade.php
<form action="/" method="post" id="dropzoneForm" class="dropzone" enctype="multipart/form-data">

</form>

@push('scripts')
<script>
    var user_id='{{$model->id}}';
    Dropzone.autoDiscover = false;
    var files = {!! json_encode($gallery->resources) !!};

    var ready=false;


    var mydropzone = new Dropzone("#dropzoneForm", {
        url: "{{ route('admin.users.gallery-store', ['id'=>$model->id]) }}",
        uploadMultiple: true,
        paramName: 'image',
        addRemoveLinks: true,
    });

    function openGallery(index=0) {
        window.open(files[index].url);
    }
    
    /*dropzone.on("removedfile", function(file) {
        var server_file = $(file.previewTemplate).children('.server_file').text();
        alert(server_file);
        // Do a post request and pass this path and use server-side language to delete the file
        $.post("delete.php", { file_to_be_deleted: server_file } );
    });*/

    function putImagesFromServer() {
        var ready=false; 
        mydropzone.removeAllFiles(true);
        
       mydropzone.on("removedfile", function (file) {
            var server_file = file.id;
            swal({
                title: 'Está seguro?',
                text: 'Está seguro que quiere eliminar esta imagen?',
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Sí, eliminar!',
                cancelButtonText: 'No, cancelar',
            }).then(function (result) {
                if (result.value) {
                    $.ajax({
                        'url': '/admin/users/delete-image/' + file.gallery_id,
                        'method': 'DELETE',
                        'data': {
                            'delete': [file.id]
                        }
                    });
                } else {
                    location.reload();
                }
            });
        });

        
        var index = 0;
        files.map(r => {
            const file = {name: r.url, size: r.size, gallery_id: r.owner_id, id: r.id, previewElement: null, index: index};
            
            mydropzone.emit('addedfile', file);
            mydropzone.emit('thumbnail', file, r.medium_image_url);
            mydropzone.emit('complete', file);

            //launch gallery
            file.previewElement.onclick = (f) => {
                this.openGallery(file.index);
            };
            mydropzone.files.push(file);
            //launch gallery
            file.previewElement.onclick = (f) => {
                openGallery(file.index);
            };
            index++;
        });
        ready=true;
    }

    putImagesFromServer();

</script>
@endpush

resources/views/admin/users/tabs/identity.blade.php
<form class="form form-horizontal form-enterkey" method="POST" action="{{ route('admin.users.identity-store', ['id'=>$model->id]) }}" autocomplete="off" enctype="multipart/form-data">
    {{ method_field('PUT') }}
    @csrf    
    @if($verification)
    @php
    $images=$verification->getIdImages();
    @endphp

    <div class="form-group has-feedback  @if($errors->has('status')) has-error @endif">
        <div class="col-sm-2"></div>

        <div class="col-sm-10">

            <div class="clearfix my-20px">
                <div class="badge pull-right status status-{{ strtolower($verification->status) }}">{{ trans('fields.verification-statuses.' . $verification->status) }}</div>
            </div>

        </div>
    </div>


    <div class="form-group">
        <label for="image" class="col-sm-2 control-label">Numero de documento: </label>
        <div class="        col-sm-10">
            <input class="form-control col-12" type="text"  value="{{ $verification->identity_id }}" disabled="" />
        </div>
    </div>

    <div class="form-group">
        <label for="image" class="col-sm-2 control-label">Pais: </label>
        <div class="col-sm-10">
            @php
            $countries=\App\Models\Country::all();
            @endphp
            <select class="select2 form-control" name="country_id" id="inputCountry">
                @foreach($countries as $country)
                <option value="{{ $country->id }}" @if(old('country_id', $verification->country_id)==$country->id) selected @endif> {{ $country->name }}</option>
                @endforeach
            </select>
            @if ($errors->has('country_id'))
            <span class="help-block">
                {{ $errors->first('country_id') }}
            </span>
            @endif
        </div>
    </div>



    <div class="form-group has-feedback">
        <label for="image" class="col-sm-2 control-label">Fotos: </label>
        <div class="col-sm-10">
            @if(count($images))
            <a href="{{  $verification->getIdImageUrl($images['front']) }}" target="_blank"><img width="200" height="200" class="image" style="border:3px solid #ddd; margin-right: 10px"  src="{{ $verification->getIdImageUrl($images['front'], '200x200') }}" /></a>
            <a href="{{ $verification->getIdImageUrl($images['back']) }}" target="_blank"><img width="200" height="200" class="image" style="border:3px solid #ddd" src="{{ $verification->getIdImageUrl($images['back'], '200x200') }}" /></a>
            @endif
        </div>
    </div>


    <div class="form-actions">
        <div class="col-sm-10 pull-right">
            <a href='{{ route('admin.users.index') }}' style="margin-right: 10px;" class="btn btn-default pull-left"><i class='fa fa-reply'></i> {{ trans('generics.cancel') }}</a>
            @can('user.update', $model)
            <a href="{{ route('admin.users.identity', ['id'=>$model->id]) . '?action=approve' }}" class="btn btn-success pull-left"><i class='fa fa-check'></i> ACEPTAR</a>
            <a href="{{ route('admin.users.identity', ['id'=>$model->id]) . '?action=reject' }}"  class="btn btn-danger pull-right"><i class='fa fa-times'></i> RECHAZAR</a>
            @endif

        </div>
    </div>
    @else
    <p class="alert alert-warning">Este usuario aún no ha solicitado verificación de identidad.</p>
    @endif

</form>

resources/views/admin/users/tabs/prices.blade.php
<form class="form form-horizontal form-enterkey" method="POST" action="{{ route('admin.users.prices-store', ['id'=>$model->id]) }}" autocomplete="off" enctype="multipart/form-data">
    {{ method_field('PUT') }}
    @csrf
    @foreach($prices as $key => $value)
    <div class="form-group has-feedback  @if ($errors->has('hours_' . $key)) has-error @endif">
        <label for="inputHours_{{ $key }}" class="col-sm-2 control-label">{{ $key }} Horas</label>

        <div class="col-sm-10">
            <input id="inputHours_{{$key}}" type="number" class="form-control{{ $errors->has('hours_' . $key) ? ' is-invalid' : '' }}" name="{{ 'hours_' . $key }}" value="{{ old('hours_' . $key , $value) }}" placeholder="Valor" required min="1">

            @if ($errors->has('hours_' . $key))
            <span class="help-block">
                {{ $errors->first('hours_' . $key) }}
            </span>
            @endif
        </div>
    </div>
    @endforeach

    <div class="form-actions">
        <div class="col-sm-10 pull-right">
            <a href='{{ route('admin.users.index') }}' style="margin-right: 10px;" class="btn btn-default pull-left"><i class='fa fa-reply'></i> {{ trans('generics.cancel') }}</a>
            @can('user.update', $model)
            <button type='submit' class="btn btn-success pull-left btn-delete"><i class='fa fa-save'></i> {{ trans('generics.save') }}</button>
            @endif
            <!--
                        @can('user.delete', $model)
                        <button type='submit' class="btn btn-danger pull-right"><i class='fa fa-trash'></i> {{ trans('generics.trash') }}</button>
                        @endif
            -->
        </div>
    </div>
</form>

resources/views/admin/users/tabs/profile.blade.php
@include('admin.users.form-profile', ['action'=>route('admin.users.profile-store', $model->id)])

resources/views/admin/users/tabs/security.blade.php
<form class="form form-horizontal form-enterkey" method="POST" action="{{ route('admin.users.security-store', ['id'=>$model->id]) }}" autocomplete="off" enctype="multipart/form-data">
    {{ method_field('PUT') }}
    @csrf

    <div class="form-group has-feedback  @if ($errors->has('password')) has-error @endif">
        <label for="inputPassword" class="col-sm-2 control-label">Nuevo password</label>

        <div class="col-sm-10">
            <input id="inputPassword" type="password" minlength="6" class="form-control{{ $errors->has('password') ? ' is-invalid' : '' }}" name="password" value="{{ old('password')}}" placeholder="{{ __('fields.password') }}" required autofocus>
            @if ($errors->has('password'))
            <span class="help-block">
                {{ $errors->first('password') }}
            </span>
            @endif
        </div>
    </div>
    
    <div class="form-group has-feedback  @if ($errors->has('password')) has-error @endif">
        <label for="inputPhoneVerified" class="col-sm-2 control-label">Telefono verificado</label>

        <div class="col-sm-10">
            <input id="inputPassword" type="checkbox" class="" name="phone_verified" value="1" @if(old('phone_verified', $model->phone_verified)) checked @endif>
           
        </div>
    </div>

    <div class="form-actions">
        <div class="col-sm-10 pull-right">
            <a href='{{ route('admin.users.index') }}' style="margin-right: 10px;" class="btn btn-default pull-left"><i class='fa fa-reply'></i> {{ trans('generics.cancel') }}</a>
            @can('user.update', $model)
            <button type='submit' class="btn btn-success pull-left btn-delete"><i class='fa fa-save'></i> {{ trans('generics.save') }}</button>
            @endif
            <!--
                        @can('user.delete', $model)
                        <button type='submit' class="btn btn-danger pull-right"><i class='fa fa-trash'></i> {{ trans('generics.trash') }}</button>
                        @endif
            -->
        </div>
    </div>
</form>