routes/admin.php
<?php

Route::get('/login', 'Auth\LoginController@showLoginForm')->name('admin.login');
Route::post('/login', 'Auth\LoginController@login');
Route::get('/forgot-password', 'Auth\LoginController@showForgotForm')->name('admin.forgot-password');


Route::group(['middleware' => ['admin', 'admin.auth', 'admin.menu']], function () {
    Route::match(array('GET', 'POST'), '/logout', 'DashboardController@logout')->name('admin.logout');
    Route::any('/', 'DashboardController@index')->name('admin.home');

    Route::resource('/pages', 'PagesController', ['as' => 'admin']);
    Route::resource('/users', 'UsersController', ['as' => 'admin']);
    Route::get('/users/{id}/profile', 'UsersController@editProfile')->name('admin.users.profile');
    Route::put('/users/{id}/profile', 'UsersController@updateProfile')->name('admin.users.profile-store');
    Route::get('/users/{id}/security', 'UsersController@editSecurity')->name('admin.users.security');
    Route::put('/users/{id}/security', 'UsersController@updateSecurity')->name('admin.users.security-store');
    Route::get('/users/{id}/appointments', 'UsersController@listAppointments')->name('admin.users.appointments');
    Route::get('/users/{id}/appointments/{appointmentId}', 'UsersController@showAppointment')->name('admin.users.appointments.detail');
    Route::put('/users/{id}/appointments', 'UsersController@updateAppointments')->name('admin.users.appointments-store');


    Route::resource('/providers', 'ProvidersController', ['as' => 'admin']);
    Route::get('/providers/{id}/profile', 'ProvidersController@editProfile')->name('admin.providers.profile');
    Route::put('/providers/{id}/profile', 'ProvidersController@updateProfile')->name('admin.providers.profile-store');
    Route::get('/providers/{id}/security', 'ProvidersController@editSecurity')->name('admin.providers.security');
    Route::put('/providers/{id}/security', 'ProvidersController@updateSecurity')->name('admin.providers.security-store');
    Route::get('/providers/{id}/appointments', 'ProvidersController@listAppointments')->name('admin.providers.appointments');
    Route::get('/providers/{id}/appointments/{appointmentId}', 'ProvidersController@showAppointment')->name('admin.providers.appointments.detail');
    Route::put('/providers/{id}/appointments', 'ProvidersController@updateAppointments')->name('admin.providers.appointments-store');
    Route::get('/providers/{id}/prices', 'ProvidersController@showPrices')->name('admin.providers.prices');
    Route::put('/providers/{id}/prices', 'ProvidersController@updatePrices')->name('admin.providers.prices-store');
    Route::get('/providers/{id}/gallery', 'ProvidersController@showGallery')->name('admin.providers.gallery');
    Route::delete('/providers/delete-image/{galleryId}', 'ProvidersController@deleteImageGallery')->name('admin.providers.gallery-delete-image');
    Route::post('/providers/{id}/gallery', 'ProvidersController@updateGallery')->name('admin.providers.gallery-store');
    Route::get('/providers/{id}/identity', 'ProvidersController@showIdentity')->name('admin.providers.identity');
    Route::put('/providers/{id}/identity', 'ProvidersController@showIdentity')->name('admin.providers.identity-store');

    Route::get('/appointments', 'AppointmentsController@index')->name('admin.appointments');
    Route::get('/appointments/{id}', 'AppointmentsController@show')->name('admin.appointments.show');

    Route::get('/maps/providers', 'MapsController@showProvidersMap')->name('admin.maps.providers');

    Route::get('/currencies', 'CurrenciesController@show')->name('admin.currencies');
    Route::put('/currencies', 'CurrenciesController@update')->name('admin.currencies.update');

    Route::resource('/automessages', 'AutoMessagesController', ['as' => 'admin']);

    Route::resource('/chats', 'ChatsController', ['as' => 'admin']);

    Route::get('/settings', 'SettingsController@index')->name('admin.settings');
    Route::post('/settings', 'SettingsController@save')->name('admin.settings.save');
    Route::get('/clear-cache', 'SettingsController@clearCache')->name('admin.artisan.cache-clear');
});

routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

Route::get('/resources/lang.json', 'LangController@index');
Route::get('/images/{section}/{folder}/{thumb}/{filename}', array('as' => 'imgs', 'uses' => 'ImagesController@dispatchImage'));
//Route::get('/downloads/resources/{uniqueId}', 'ResourceFilesController@download')->name('resources.download');


#Route::get('/', 'AngularController@serve');
#Route::get('{any?}', 'AngularController@serve')->where('any', '.*'); // this will ensure all routes will serve index.php file

app/Models/AutoMessage.php
<?php

namespace App\Models;

class AutoMessage extends UUIDModel {

    protected $guarded = [];

}

app/Http/Controllers/Admin/AutoMessagesController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Models\AutoMessage;
use Illuminate\Support\Facades\Cache;

class AutoMessagesController extends Controller {

    public function __construct() {
        ;
    }

    public function index(\App\DataTables\Admin\AutoMessagesDataTable $dataTable) {
        return $dataTable->render('admin.automessages.index');
    }

    public function show(Request $request, $id) {
        return redirect(route('admin.automessages.edit', ['id' => $id]));
    }

    public function edit(Request $request, $id) {
        $autoMessage = AutoMessage::findOrFail($id);
        return view('admin.automessages.detail')->with(['model' => $autoMessage]);
    }

    public function create(Request $request) {
        return view('admin.automessages.create')->with(['model' => new AutoMessage()]);
    }

    public function store(Request $request) {
        //$autoMessage = ;
        /* if ($validator->fails()) {
          return redirect()->back()->withInput()->withErrors($validator);
          } */
        AutoMessage::create($request->input());
        Cache::forget('automessages');
        return redirect(route('admin.automessages.index'))->with(['message' => __('generics.data_saved_successfully')]);
    }

    public function update(Request $request, $id) {

        $autoMessage = AutoMessage::findOrFail($id);
        Cache::forget('automessages');
        $autoMessage->update($request->input());
        return redirect()->back()->withInput()->with(['message' => __('generics.data_saved_successfully')]);
    }

    public function destroy(Request $request, $id) {
        $autoMessage = AutoMessage::findOrFail($id);
        $autoMessage->delete();
        Cache::forget('automessages');
        return (new \App\Lib\Api\JSONResponse())->render();
    }

}

app/Http/Controllers/Api/Admin/AutoMessagesController.php
<?php

namespace App\Http\Controllers\Api\Admin;

use Illuminate\Http\Request;
use App\Models\Appointment;
use App\Models\User;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;
use App\Models\AutoMessage;
use Illuminate\Support\Facades\Cache;

/**
 * Description of AutomessagesController
 *
 * @author pablo
 */
class AutomessagesController extends \App\Http\Controllers\Api\BaseController
{
    public function index(Request $request)
    {
        $response = $this->getResponseInstance();
        $response->setPayload(AutoMessage::orderBy('position')->get());
        return $this->renderResponse();
    }

    public function show(Request $request, $id)
    {
        $autoMessage = AutoMessage::findOrFail($id);
        $response = $this->getResponseInstance();
        $response->setPayload($autoMessage);
        return $this->renderResponse();
    }

    public function store(Request $request)
    {
        $autoMessage = AutoMessage::create($request->only('position', 'send_to', 'message', 'enabled'));
        Cache::forget('automessages');
        $response = $this->getResponseInstance();
        $response->setPayload($autoMessage);
        return $this->renderResponse();
    }

    public function update(Request $request, $id)
    {
        $autoMessage = AutoMessage::findOrFail($id);
        Cache::forget('automessages');
        $autoMessage->update($request->only('position', 'send_to', 'message', 'enabled'));
        $response = $this->getResponseInstance();
        $response->setPayload($autoMessage);
        return $this->renderResponse();
    }

    public function destroy(Request $request, $id)
    {
        $autoMessage = AutoMessage::findOrFail($id);
        $autoMessage->delete();
        Cache::forget('automessages');
        $response = $this->getResponseInstance();
        $response->setPayload(['success' => true]);
        $response->setStatusMessage("Elemento eliminado correctamente");
        return $this->renderResponse();
    }
}

resources/views/admin/automessages/create.blade.php
@extends('admin.layouts.app')
@section('page.title') Crear Mensaje @endsection
@section('content')
<section class="content"> 

    <form class="form" action="{{ route('admin.automessages.store', ['id'=>$model->id]) }}" method="post" enctype="multipart/form-data">
        {{ method_field('POST') }}
        @csrf
        @include('admin.automessages.form', ['mode'=>'create', 'model'=>$model]) 
        <div class="form-actions">
            <a href="{{ route('admin.automessages.index') }}" class="btn btn-default pull-left"><i class="fa fa-reply"></i> Cancelar</a>
            <button type="submit" class="btn btn-success"><i class="fa fa-save"></i> Guardar cambios</button>
        </div>
    </form>

</section>
@endsection

resources/views/admin/automessages/detail.blade.php
@extends('admin.layouts.app')
@section('page.title') Editar Mensaje @endsection
@section('content')
<section class="content"> 

    <form class="form" action="{{ route('admin.automessages.update', ['id'=>$model->id]) }}" method="post" enctype="multipart/form-data">
        {{ method_field('PUT') }}
        @csrf
        @include('admin.automessages.form', ['mode'=>'edit', 'model'=>$model]) 
        <div class="form-actions">
            <a href="{{ route('admin.automessages.index') }}" class="btn btn-default pull-left"><i class="fa fa-reply"></i> Cancelar</a>
            <button type="submit" class="btn btn-success"><i class="fa fa-save"></i> Guardar cambios</button>
        </div>
    </form>

</section>
@endsection

resources/views/admin/automessages/form.blade.php
<input type="hidden" value="{{ $model->id }}" name="id" />
<div class="form-group row">
    <label for="title" class="col-12 col-md-2 col-form-label">Posicion</label>
    <div class="col-12 col-md-10">
        <input id="title" type="number" style="width: 150px" min="0" class="form-control {{ $errors->has('position') ? ' is-invalid' : '' }}" required name="position" value="{{ old('position', $model->position) }}" autofocus>
        @if ($errors->has('position'))
        <span class="invalid-feedback">
            <strong>{{ $errors->first('position') }}</strong>
        </span>
        @endif
    </div>
</div>

<div class="form-group row">
    <label for="title" class="col-12 col-md-2 col-form-label">Destinatario</label>
    <div class="col-12 col-md-10">
        <select class="form-control" required name="send_to" style="width: 250px">
            <option value="">Seleccionar</option>
            <option value="USER" @if(old('send_to', $model->send_to)=='USER')selected @endif>Cliente</option>
            <option value="PROVIDER" @if(old('send_to', $model->send_to)=='PROVIDER')selected @endif>Modelo</option>
            <option value="BOTH" @if(old('send_to', $model->send_to)=='BOTH')selected @endif>Ambos</option>
        </select>
        @if ($errors->has('send_to'))
        <span class="invalid-feedback">
            <strong>{{ $errors->first('send_to') }}</strong>
        </span>
        @endif
    </div>
</div>

<div class="form-group row">
    <label for="body" class="col-12 col-md-2 col-form-label">Mensaje</label>
    <div class="col-12 col-md-10">
        <textarea class="form-control {{ $errors->has('message') ? ' is-invalid' : '' }}" required name="message">{{ old('message', $model->message) }}</textarea>
        @if ($errors->has('message'))
        <span class="invalid-feedback">
            <strong>{{ $errors->first('message') }}</strong>
        </span>
        @endif
    </div>
</div>

resources/views/admin/automessages/index.blade.php
@extends('admin.layouts.app')
@section('page.title') Mensajes automaticos @endsection
@section('content')
<div class="top-filter clearfix">
    <a href="{{ route('admin.automessages.create') }}" class="btn btn-success pull-right" style="margin-right: 12px;"><i class="fa fa-plus"></i> Crear nuevo</a>
</div>


{!! $dataTable->table(['class' => 'table table-bordered table-striped dataTable', 'id' => 'automessages-table']) !!}
@endsection

@push('scripts')
{!! $dataTable->scripts() !!}

@endpush

resources/views/admin/automessages/table-actions.blade.php
<div class="text-center">
    <a class="btn btn-default btn-xs btn-primary" href="{{ route('admin.automessages.show', ['id'=>$id])}}"><i class="fa fa-edit"></i></a>
    <a class="btn btn-default btn-xs btn-danger btn-delete" href="#" data-action='{{ route('admin.automessages.destroy', ['id'=>$id])}}'><i class="fa fa-trash"></i></a>
</div>