routes/admin.php
<?php

Route::get('/login', 'Auth\LoginController@showLoginForm')->name('admin.login');
Route::post('/login', 'Auth\LoginController@login');
Route::get('/forgot-password', 'Auth\LoginController@showForgotForm')->name('admin.forgot-password');


Route::group(['middleware' => ['admin', 'admin.auth', 'admin.menu']], function () {
    Route::match(array('GET', 'POST'), '/logout', 'DashboardController@logout')->name('admin.logout');
    Route::any('/', 'DashboardController@index')->name('admin.home');

    Route::resource('/pages', 'PagesController', ['as' => 'admin']);
    Route::resource('/users', 'UsersController', ['as' => 'admin']);
    Route::get('/users/{id}/profile', 'UsersController@editProfile')->name('admin.users.profile');
    Route::put('/users/{id}/profile', 'UsersController@updateProfile')->name('admin.users.profile-store');
    Route::get('/users/{id}/security', 'UsersController@editSecurity')->name('admin.users.security');
    Route::put('/users/{id}/security', 'UsersController@updateSecurity')->name('admin.users.security-store');
    Route::get('/users/{id}/appointments', 'UsersController@listAppointments')->name('admin.users.appointments');
    Route::get('/users/{id}/appointments/{appointmentId}', 'UsersController@showAppointment')->name('admin.users.appointments.detail');
    Route::put('/users/{id}/appointments', 'UsersController@updateAppointments')->name('admin.users.appointments-store');


    Route::resource('/providers', 'ProvidersController', ['as' => 'admin']);
    Route::get('/providers/{id}/profile', 'ProvidersController@editProfile')->name('admin.providers.profile');
    Route::put('/providers/{id}/profile', 'ProvidersController@updateProfile')->name('admin.providers.profile-store');
    Route::get('/providers/{id}/security', 'ProvidersController@editSecurity')->name('admin.providers.security');
    Route::put('/providers/{id}/security', 'ProvidersController@updateSecurity')->name('admin.providers.security-store');
    Route::get('/providers/{id}/appointments', 'ProvidersController@listAppointments')->name('admin.providers.appointments');
    Route::get('/providers/{id}/appointments/{appointmentId}', 'ProvidersController@showAppointment')->name('admin.providers.appointments.detail');
    Route::put('/providers/{id}/appointments', 'ProvidersController@updateAppointments')->name('admin.providers.appointments-store');
    Route::get('/providers/{id}/prices', 'ProvidersController@showPrices')->name('admin.providers.prices');
    Route::put('/providers/{id}/prices', 'ProvidersController@updatePrices')->name('admin.providers.prices-store');
    Route::get('/providers/{id}/gallery', 'ProvidersController@showGallery')->name('admin.providers.gallery');
    Route::delete('/providers/delete-image/{galleryId}', 'ProvidersController@deleteImageGallery')->name('admin.providers.gallery-delete-image');
    Route::post('/providers/{id}/gallery', 'ProvidersController@updateGallery')->name('admin.providers.gallery-store');
    Route::get('/providers/{id}/identity', 'ProvidersController@showIdentity')->name('admin.providers.identity');
    Route::put('/providers/{id}/identity', 'ProvidersController@showIdentity')->name('admin.providers.identity-store');

    Route::get('/appointments', 'AppointmentsController@index')->name('admin.appointments');
    Route::get('/appointments/{id}', 'AppointmentsController@show')->name('admin.appointments.show');

    Route::get('/maps/providers', 'MapsController@showProvidersMap')->name('admin.maps.providers');

    Route::get('/currencies', 'CurrenciesController@show')->name('admin.currencies');
    Route::put('/currencies', 'CurrenciesController@update')->name('admin.currencies.update');

    Route::resource('/automessages', 'AutoMessagesController', ['as' => 'admin']);

    Route::resource('/chats', 'ChatsController', ['as' => 'admin']);

    Route::get('/settings', 'SettingsController@index')->name('admin.settings');
    Route::post('/settings', 'SettingsController@save')->name('admin.settings.save');
    Route::get('/clear-cache', 'SettingsController@clearCache')->name('admin.artisan.cache-clear');
});

routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

Route::get('/resources/lang.json', 'LangController@index');
Route::get('/images/{section}/{folder}/{thumb}/{filename}', array('as' => 'imgs', 'uses' => 'ImagesController@dispatchImage'));
//Route::get('/downloads/resources/{uniqueId}', 'ResourceFilesController@download')->name('resources.download');


#Route::get('/', 'AngularController@serve');
#Route::get('{any?}', 'AngularController@serve')->where('any', '.*'); // this will ensure all routes will serve index.php file

app/Http/Controllers/Admin/ProvidersController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Admin\Controller;
use App\Models\User;

class ProvidersController extends Controller {

    public function index(\App\DataTables\Admin\ProvidersDataTable $dataTable) {
        /* $savedFilter = $this->getRequestSavedParams('users.index');
          if ($savedFilter) {
          return redirect()->to(route('admin.providers.index', $savedFilter));
          }
          $this->saveRequestToSession('users.index'); */
        return $dataTable->render('admin.providers.index');
    }

    public function show(Request $request, $id) {

        return $this->edit($request, $id);
    }

    public function edit(Request $request, $id) {
        $user = User::where(['id' => $id, 'role' => 'PROVIDER'])->with(['profile'])->firstOrFail();
        if (!$user->profile) {
            $user->profile()->save(new \App\Models\UserProfile());
        }
        $user->profile;
        return view('admin.providers.detail')->with(['model' => $user, 'profile' => $user->profile, 'tab' => 'basic']);
    }

    public function editProfile(Request $request, $id) {
        $user = User::where(['id' => $id, 'role' => 'PROVIDER'])->with(['profile'])->firstOrFail();
        if (!$user->profile) {
            $user->profile()->save(new \App\Models\UserProfile());
        }
        $user->profile;
        return view('admin.providers.detail')->with(['model' => $user, 'profile' => $user->profile, 'tab' => 'profile']);
    }

    public function update(Request $request, $id) {
        $user = User::where(['id' => $id, 'role' => 'PROVIDER'])->firstOrFail();
        $validator = User::getValidator($request->input(), $user);
        if ($validator->fails()) {
            return redirect()->back()->withInput()->withErrors($validator);
        }



        $user->profile()->updateOrCreate(['user_id' => $user->id], $request->input('profile', []));
        $user->update($request->input());


        if ($request->file('image')) {
            $user->saveImage($request->file('image'));
            $user->save();
        }

        return redirect()->back()->withInput()->with(['message' => 'Usuario guardado correctamente!']);
    }

    public function updateProfile(Request $request, $id) {
        $user = User::where(['id' => $id, 'role' => 'PROVIDER'])->firstOrFail();
        $validator = User::getValidator($request->input(), $user);
        if ($validator->fails()) {
            return redirect()->back()->withInput()->withErrors($validator);
        }
        $user->profile()->updateOrCreate(['user_id' => $user->id], $request->input('profile', []));
        $user->update($request->input());
        return redirect()->back()->withInput()->with(['message' => 'Usuario guardado correctamente!']);
    }

    public function editSecurity(Request $request, $id) {
        $user = User::where(['id' => $id, 'role' => 'PROVIDER'])->with(['profile'])->firstOrFail();

        return view('admin.providers.detail')->with(['model' => $user, 'profile' => $user->profile, 'tab' => 'security']);
    }

    public function updateSecurity(Request $request, $id) {
        $user = User::where(['id' => $id, 'role' => 'PROVIDER'])->with(['profile'])->firstOrFail();
        if ($request->get('password')) {
            $user->password = \Illuminate\Support\Facades\Hash::make($request->get('password'));
        }

        if ($request->get('phone_verified')) {
            $user->phone_verified = 1;
        }
        $user->save();
        if ($request->get('password')) {
            \App\Lib\SMSManager::getInstance()->sendSMS($user->completePhone(), 'Hola ' . $user->name . ' tu nuevo password en vaceate.com es ' . $request->get('password'));
        }
        return redirect()->back()->withInput()->with(['message' => 'Usuario guardado correctamente!']);
    }

    public function listAppointments(Request $request, \App\DataTables\Admin\AppointmentsDataTable $dataTable, $id) {
        $user = User::where(['id' => $id, 'role' => 'PROVIDER'])->with(['profile'])->firstOrFail();
        return $dataTable->with(['user' => $user, 'status' => $request->get('status', 'all')])->render('admin.providers.detail', ['model' => $user, 'tab' => 'appointments']);
    }

    public function showAppointment(Request $request, $id, $appointmentId) {
        $user = User::where(['id' => $id, 'role' => 'PROVIDER'])->with(['profile'])->firstOrFail();
        $appointment = \App\Models\Appointment::where(['id' => $appointmentId, 'provider_id' => $id])->firstOrFail();
        return view('admin.appointments.detail', ['model' => $appointment, 'backUrl' => route('admin.providers.appointments', ['id' => $id])]);
    }

    public function showGallery(Request $request, $id) {
        $user = User::where(['id' => $id, 'role' => 'PROVIDER'])->with(['profile'])->firstOrFail();
        $gallery = $user->gallery;
        if ($user->gallery->isDirty()) {
            $gallery->id = \Ramsey\Uuid\Uuid::uuid4();
            $gallery->owner_id = $user->id;
            $gallery->owner_type = User::class;
            $gallery->save();
        }
        $gallery->resources;
        return view('admin.providers.detail', ['model' => $user, 'tab' => 'gallery', 'gallery' => $gallery]);
    }

    public function updateGallery(Request $request, $id) {
        $user = User::where(['id' => $id, 'role' => 'PROVIDER'])->with(['profile'])->firstOrFail();
        $gallery = $user->gallery;
        if ($user->gallery->isDirty()) {
            $gallery->id = \Ramsey\Uuid\Uuid::uuid4();
            $gallery->owner_id = $user->id;
            $gallery->owner_type = User::class;
            $gallery->save();
        }

        $files = $request->file('image');

        foreach ($files as $file) {
            $resource = new \App\Models\GalleryImage();
            $resource->owner_type = Gallery::class;
            $resource->owner_id = $gallery->id;
            $resource->mime_type = $file->getMimeType();
            $resource->size = $file->getSize() / 1024;
            $resource->saveImage($file);
            $gallery->resources()->save($resource);
        }

        $gallery->save();
        $gallery->resources;

        $jsonResponse = new \App\Lib\Api\JSONResponse();
        $jsonResponse->setStatusMessage(__('generics.data_saved_successfully'));
        $jsonResponse->setPayload(new \App\Http\Resources\GalleryResource($gallery));
        return $jsonResponse->render();
    }

    public function showPrices(Request $request, $id) {
        $user = User::where(['id' => $id, 'role' => 'PROVIDER'])->with(['profile'])->firstOrFail();
        $priceOptions = config('custom.price_options');
        $prices = [];
        foreach ($priceOptions as $option) {
            $price = $user->prices()->where(['hours' => $option])->first();
            $value = $price ? $price->value : 0;
            $prices[$option] = $value / 100;
        }
        return view('admin.providers.detail', ['model' => $user, 'tab' => 'prices', 'prices' => $prices]);
    }

    public function updatePrices(Request $request, $userId) {
        $user = User::where(['id' => $userId, 'role' => 'PROVIDER'])->with(['profile'])->firstOrFail();

        $priceOptions = config('custom.price_options');
        $rules = [];
        foreach ($priceOptions as $opt) {
            $rules['hours_' . $opt] = 'required|integer|min:100';
        }



        $formattedPrices = [];
        foreach ($priceOptions as $opt) {
            $price = $request->get('hours_' . $opt, 0);
            $formattedPrices[('hours_' . $opt)] = $price * 100;
        }


        $validator = \Illuminate\Support\Facades\Validator::make($formattedPrices, $rules);
        if ($validator->fails()) {
            return redirect()->back()->withInput()->withErrors($validator)->with(['error' => __('generics.invalid_data')]);
        }

        $user->prices()->delete();
        foreach ($priceOptions as $key) {
            $fprice = $formattedPrices['hours_' . $key];
            $price = [];
            $price['hours'] = $key;
            $price['provider_id'] = $user->id;
            $price['currency'] = 'USD';
            $price['value'] = $fprice;
            $sPrice = \App\Models\ProviderPrice::create($price);
        }
        return redirect()->back()->withInput()->with(['message' => __('generics.data_saved_successfully')]);
    }

    public function deleteImageGallery(Request $request, $id) {
        $gallery = \App\Models\Gallery::findOrFail($id);
        if (!$gallery) {
            abort(404);
        }

        $toRemove = $request->get('delete');
        foreach ($toRemove as $id) {
            $resource = $gallery->resources()->where('id', $id)->firstOrFail();
            $resource->deleteImage();
            $resource->delete();
        }
        $jsonResponse = new \App\Lib\Api\JSONResponse();
        $jsonResponse->setStatusMessage(__('generics.data_saved_successfully'));
        $gallery->resources;
        $jsonResponse->setPayload(new \App\Http\Resources\GalleryResource($gallery));
        return $jsonResponse->render();
    }

    public function showIdentity(Request $request, $id) {
        $user = User::where(['id' => $id, 'role' => 'PROVIDER'])->with(['profile', 'country'])->firstOrFail();

        $verification = $user->idVerificationRequest;
        if (!$verification) {
            $verification = new \App\Models\IdentityVerificationRequest();
            $verification->user_id = $user->id;
            $verification->country_id = $user->country->id;
            $verification->status = 'PENDING';
        }
        $action = $request->get('action', null);
        if ($verification && $action) {
            if ($request->method() === 'PUT') {
                $rules = [
                    'identity_id' => 'required|string|min:4',
                    'country_id' => 'required|exists:countries,id',
                ];

                if (!$verification->exists) {

resources/views/admin/providers/detail.blade.php
@extends('admin.layouts.app')
@section('page.title') User: {{$model->id}} - {{ $model->name }}@endsection
@section('content')
<div class="nav-tabs-custom">
    <ul class="nav nav-tabs">
        <li class="@if($tab==='basic') active @endif"><a href="{{ route('admin.providers.edit', ['id'=>$model->id]) }}" aria-expanded="@if($tab==='basic') true @else false @endif">Datos</a></li>
        <li class="@if($tab==='profile') active @endif"><a href="{{ route('admin.providers.profile', ['id'=>$model->id]) }}" aria-expanded="@if($tab==='profile') true @else false @endif">Perfil <span class="status status-{{ strtolower($model->status) }}">{{$model->status}}</span></a></li>
        <li class="@if($tab==='identity') active @endif"><a href="{{ route('admin.providers.identity', ['id'=>$model->id]) }}" aria-expanded="@if($tab==='identity') true @else false @endif">Identidad <span class="status status-{{  (($model->identity_verified)? 'active':'pending') }}">{{(($model->identity_verified)? 'Verificada':'Pendiente')}}</span></a></li>
        <li class="@if($tab==='security') active @endif"><a href="{{ route('admin.providers.security', ['id'=>$model->id]) }}" aria-expanded="@if($tab==='security') true @else false @endif">Seguridad</a></li>
        <li class="@if($tab==='prices') active @endif"><a href="{{ route('admin.providers.prices', ['id'=>$model->id]) }}" aria-expanded="@if($tab==='prices') true @else false @endif">Precios</a></li>
        <li class="@if($tab==='gallery') active @endif"><a href="{{ route('admin.providers.gallery', ['id'=>$model->id]) }}" aria-expanded="@if($tab==='gallery') true @else false @endif">Galería</a></li>
        <li class="@if($tab==='appointments') active @endif"><a href="{{ route('admin.providers.appointments', ['id'=>$model->id]) }}" aria-expanded="@if($tab==='appointments') true @else false @endif">Citas</a></li>

    </ul>
    <div class="tab-content">
        <div class="tab-pane active" id="tab_data">
            @include('admin.providers.tabs.' . $tab)
        </div>

    </div>
    <!-- /.tab-content -->
</div>


@endsection
@push('scripts')

@endpush

resources/views/admin/providers/form-profile.blade.php
<form class="form form-horizontal form-enterkey" method="POST" action="{{ $action }}" autocomplete="off" enctype="multipart/form-data">
    {{ method_field('PUT') }}
    @csrf

    @if($model->profile_status == 'pending')
    <div class="alert alert-warning clearfix alert-dismissible">{!! trans('admin_messages.profile-info-pending', ['link'=> route('admin.account-validations.get-by-user', ['id'=>$model->id])]) !!}</div>
    @endif




    <div class="form-group has-feedback  @if($errors->has('status')) has-error @endif">
        <div class="col-sm-2"></div>

        <div class="col-sm-10">

            <div class="clearfix my-20px">
                <div class="badge pull-right status status-{{ strtolower($model->status) }}">{{ trans('fields.user-statuses.' . $model->status) }}</div>
            </div>

        </div>
    </div>


    <div class="form-group has-feedback  @if($errors->has('profile[first_name]')) has-error @endif">
        <label for="inputEmail" class="col-sm-2 control-label">{{ trans('fields.first_name') }}</label>
        <div class="col-sm-10">
            <input id="first_name" type="text" class="form-control{{ $errors->has('profile[first_name]') ? ' is-invalid' : '' }}" name="profile[first_name]" value="{{ old('profile[first_name]', $model->profile->first_name) }}" placeholder="{{ __('fields.first_name') }}" >
            <span class="glyphicon glyphicon-user form-control-feedback"></span>
            @if($errors->has('profile[first_name]'))
            <span class="help-block">
                {{ $errors->first('profile[first_name]') }}
            </span>
            @endif
        </div>
    </div>

    <div class="form-group has-feedback  @if($errors->has('profile[last_name]')) has-error @endif">
        <label for="inputEmail" class="col-sm-2 control-label">{{ trans('fields.last_name') }}</label>
        <div class="col-sm-10">
            <input id="last_name" type="text" class="form-control{{ $errors->has('profile[last_name]') ? ' is-invalid' : '' }}" name="profile[last_name]" value="{{ old('profile[last_name]', $model->profile->last_name) }}" placeholder="{{ __('fields.last_name') }}" >
            <span class="glyphicon glyphicon-user form-control-feedback"></span>
            @if($errors->has('profile[last_name]'))
            <span class="help-block">
                {{ $errors->first('profile[last_name]') }}
            </span>
            @endif
        </div>
    </div>

    <div class="form-group has-feedback  @if ($errors->has('profile[country_id]')) has-error @endif">
        <label for="inputCountry" class="col-sm-2 control-label">Nacionalidad:</label>
        <div class="col-sm-10">
            @php
            $countries=\App\Models\Country::all();
            @endphp
            <select class="select2 form-control" name="profile[country_id]" id="inputCountry">
                <option value="">Seleccionar</option>
                @foreach($countries as $country)
                <option value="{{ $country->id }}" @if(old('profile[country_id]', $model->profile->country_id)==$country->id) selected @endif>{{ $country->name }}</option>
                @endforeach
            </select>
            @if ($errors->has('profile[country_id]'))
            <span class="help-block">
                {{ $errors->first('profile[country_id]') }}
            </span>
            @endif
        </div>
    </div>


    <div class="form-group has-feedback  @if($errors->has('profile[hair_color]')) has-error @endif">
        <label for="inputHair" class="col-sm-2 control-label">{{ trans('fields.hair_color') }}</label>
        <div class="col-sm-10">           
            <select class="form-control" name="profile[hair_color]" id="inputHair" style="width: 220px">                
                <option value="">Seleccionar</option>
                @foreach(config('custom.hair_colors') as $key=>$value)
                <option @if(old('profile[hair_color]', $model->profile->hair_color)===$key) selected @endif  value="{{$key}}">{{$value}}</option>
                @endforeach
            </select>
            @if($errors->has('profile[hair_color]'))
            <span class="help-block">
                {{ $errors->first('profile[hair_color]') }}
            </span>
            @endif
        </div>
    </div>

    <div class="form-group has-feedback  @if($errors->has('profile[eyes_color]')) has-error @endif">
        <label for="inputEyes" class="col-sm-2 control-label">{{ trans('fields.eyes_color') }}</label>
        <div class="col-sm-10">           
            <select class="form-control" name="profile[eyes_color]" id="inputEyes" style="width: 220px">                
                <option value="">Seleccionar</option>
                @foreach(config('custom.eyes_colors') as $key=>$value)
                <option @if(old('profile[eyes_color]', $model->profile->eyes_color)===$key) selected @endif  value="{{$key}}">{{$value}}</option>
                @endforeach
            </select>
            @if($errors->has('profile[eyes_color]'))
            <span class="help-block">
                {{ $errors->first('profile[eyes_color]') }}
            </span>
            @endif
        </div>
    </div>

    <div class="form-group has-feedback  @if($errors->has('profile[skin_color]')) has-error @endif">
        <label for="inputSkin" class="col-sm-2 control-label">{{ trans('fields.skin_color') }}</label>
        <div class="col-sm-10">           
            <select class="form-control" name="profile[skin_color]" id="inputSkin" style="width: 220px">                
                <option value="">Seleccionar</option>
                @foreach(config('custom.skin_colors') as $key=>$value)
                <option @if(old('profile[skin_color]', $model->profile->skin_color)===$key) selected @endif  value="{{$key}}">{{$value}}</option>
                @endforeach
            </select>
            @if($errors->has('profile[skin_color]'))
            <span class="help-block">
                {{ $errors->first('profile[skin_color]') }}
            </span>
            @endif
        </div>
    </div>

    <div class="form-group has-feedback  @if($errors->has('profile[corporal_complexion]')) has-error @endif">
        <label for="inputCorporalComplexion" class="col-sm-2 control-label">{{ trans('fields.corporal_complexion') }}</label>
        <div class="col-sm-10">           
            <select class="form-control" name="profile[corporal_complexion]" id="inputCorporalComplexion" style="width: 220px">                
                <option value="">Seleccionar</option>
                @foreach(config('custom.corporal_complexions') as $key=>$value)
                <option @if(old('profile[corporal_complexion]', $model->profile->corporal_complexion)===$key) selected @endif  value="{{$key}}">{{$value}}</option>
                @endforeach
            </select>
            @if($errors->has('profile[corporal_complexion]'))
            <span class="help-block">
                {{ $errors->first('profile[corporal_complexion]') }}
            </span>
            @endif
        </div>
    </div>

    <div class="form-group has-feedback  @if($errors->has('profile[sexual_orientation]')) has-error @endif">
        <label for="inputSexualOrientation" class="col-sm-2 control-label">{{ trans('fields.sexual_orientation') }}</label>
        <div class="col-sm-10">           
            <select class="form-control" name="profile[sexual_orientation]" id="inputSexualOrientation" style="width: 220px">                
                <option value="">Seleccionar</option>
                @foreach(config('custom.sexual_orientations') as $key=>$value)
                <option @if(old('profile[sexual_orientation]', $model->profile->sexual_orientation)===$key) selected @endif  value="{{$key}}">{{$value}}</option>
                @endforeach
            </select>
            @if($errors->has('profile[sexual_orientation]'))
            <span class="help-block">
                {{ $errors->first('profile[sexual_orientation]') }}
            </span>
            @endif
        </div>
    </div>

    <div class="form-actions">
        <div class="col-sm-10 pull-right">
            <a href='{{ route('admin.providers.index') }}' style="margin-right: 10px;" class="btn btn-default pull-left"><i class='fa fa-reply'></i> {{ trans('generics.cancel') }}</a>
            @can('user.update', $model)
            <button type='submit' class="btn btn-success pull-left btn-delete"><i class='fa fa-save'></i> {{ trans('generics.save') }}</button>
            @endif

        </div>
    </div>
</form>

resources/views/admin/providers/index.blade.php
@extends('admin.layouts.app')
@section('page.title') Proveedores @endsection
@section('content')
<div class="top-filter clearfix">
    <div class="btn-group pull-right">
        <a href="{{ route('admin.providers.index') }}?status=active" class="btn btn-default @if(request('status')=='' || request('status')=='active') active @endif">Activos</a>
        <a href="{{ route('admin.providers.index') }}?status=pending" class="btn btn-default @if(request('status')=='pending') active @endif">Pendientes</a>
        <a href="{{ route('admin.providers.index') }}?status=all" class="btn btn-default @if(request('status')=='all') active @endif">Todos</a>
    </div>
</div>




{!! $dataTable->table(['class' => 'table table-bordered table-striped dataTable', 'id' => 'providers-table']) !!}


@endsection

@push('scripts')
{!! $dataTable->scripts() !!}

@endpush

resources/views/admin/providers/table-actions.blade.php
<div class="text-center">
    <a class="btn btn-default btn-xs btn-primary" href="{{ route('admin.providers.edit', ['id'=>$id])}}"><i class="fa fa-edit"></i></a>
    <a class="btn btn-default btn-xs btn-danger btn-delete" href='{{$id}}'><i class="fa fa-trash"></i></a>
</div>